old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    producers:
        new_role:
            connection: default
            class: Rest\Infrastructure\Domain\Messages\NewRoleCreatedMessage
            exchange_options:
                name: 'new_role'
                type: 'fanout'
        role_deleted:
            connection: default
            class: Rest\Infrastructure\Domain\Messages\RoleHasBeenDeletedMessageService
            exchange_options:
                name: 'role_deleted'
                type: 'fanout'
    consumers:
        new_user:
            connection:       default
            exchange_options: {name: 'new_role', type: fanout}
            queue_options:    {name: 'new_role'}
            callback:         Rest\Infrastructure\Domain\Consumers\ProcessNewUserCreatedEvent
