Settings\Domain\Entity\Values\Setting:
  type: entity
  table: Settings
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    name:
      type: string
    type:
      type: string
    value:
      type: string
