Settings\Domain\Entity\Role:
  type: entity
  table: Roles
  repositoryClass: Settings\Infrastructure\Repositories\RoleRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    role:
      type: string
      unique: true
    name:
      type: string
      unique: true
  manyToMany:
    permissions:
      targetEntity: Settings\Domain\Entity\Permission
      inversedBy: roles
