Rest\Domain\Entity\User\UserSettings:
  type: entity
  table: user_settings
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  manyToOne:
    user:
      targetEntity: Rest\Domain\Entity\User\User
      inversedBy: settings

  manyToMany:
    userSettingsItems:
      targetEntity: Rest\Domain\Entity\User\UserSettingsItem
      mappedBy: userSettings

  fields:
    app:
      type: string
