Rest\Domain\Entity\User\UserSettingsItem:
  type: entity
  table: user_settings_item
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  manyToMany:
    userSettings:
      targetEntity: Rest\Domain\Entity\User\UserSettings
      inversedBy: userSettingsItems

  fields:
    name:
      type: string
    value:
      type: string
